### ISSUE TITLE
Quaternion changes

### ISSUE THREAD

**Issue by ElvinC** [ilya-epifanov/gyroflow-ofx#5]
Hi! Although I haven't tried your plugin yet (been learning some C++ and working on a plugin as well), just wanted to let you know that the output stabilization transform quaternions have been modified slightly to make better mathematical sense. See the dev branch here: https://github.com/ElvinC/gyroflow/blob/dev/calibrate_video.py#L351

Cheers

**Comment by ilya-epifanov** [comment]
@ElvinC somehow I missed this ticket. Thanks for the heads-up, I've actually fixed it a couple of days ago.

**Comment by ElvinC** [comment]
Awesome. I saw that you added some built packages. I'll make sure to have a try when I get a chance. Great work!

**Comment by ilya-epifanov** [comment]
Yeah, I had to completely remove OpenCV by rewriting the algorithms in rust just because packaging third-party libraries is such a PITA. Also, OpenCV didn't work 100% when loaded in Resolve's address space, so it didn't even try to use OpenCL. Good thing is that I parallelized the algorithms and they're now much faster than what OpenCV provides.
